### ISSUE TITLE
Direct RNA seq

### ISSUE THREAD

**Issue by callumparr** [NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273#1]
You could have gotta a better assembly and potentially sequenced modified bases using direct RNA sequencing. I have a basecaller than can recognize n1-methylpseudouridine.

**Comment by smmaguire** [comment]
Hi, Could you direct me to the basecaller? I have a direct RNA dataset of this.
