### ISSUE TITLE
Need comparison of sequences.

### ISSUE THREAD

**Issue by vschulz** [NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273#15]
It would be very helpful to include a sequence alignment (using MUSCLE or other method) of these two sequences with a reference COVID spike protein mRNA.

**Comment by MovGP0** [comment]
In the paper, the aligments are marked in red and they are identical to the spike protein sequence. 

See also #16

**Comment by endolith** [comment]
It would be good to show them side-by-side with the original SARS-CoV-2 genome, showing which parts are identical between the three and which parts differ.
