### ISSUE TITLE
identical coding parts?

### ISSUE THREAD

**Issue by noranekonobokkusu** [NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273#16]
Hello,

so I've translated the orange regions from figure 1 and figure 2 and they seem identical to me. Could you kindly confirm that?

Thanks!

**Comment by thathert** [comment]
Interesting! I'm getting the same result as you.

**Comment by bbascbr** [comment]
The first part is the same. But the last 585 bases of the Moderna material are extra and encode the haemoglobin...
![Screenshot from 2021-08-25 17-11-15](https://user-images.githubusercontent.com/9135732/130817391-d3a303dc-76fb-482a-b216-0ca1e70ff1a1.png)
