### ISSUE TITLE
.fasta files?

### ISSUE THREAD

**Issue by bryan-lunt** [NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273#18]
It would be nice to have .fa files of the sequences, instead of needing to copy and paste them from a PDF.

**Comment by bryan-lunt** [comment]
Someone has a pull request that includes them.

**Comment by bryan-lunt** [comment]
https://github.com/NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273/pull/3

**Comment by fswair** [comment]
If I were a scientist, I want to develop this Project to eradicate the virus. Good luck guys.

@FSWAIR

**Comment by NAalytics** [comment]
Done
