### ISSUE TITLE
Vice news is a literal pile of excrement. that is all.

### ISSUE THREAD

**Issue by ervinyoung** [NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273#2]

**Comment by TyraelElDruin** [comment]
This repo is incredibly interesting and very awesome - just wanted to throw in my $0.02. 🙂

**Comment by riichard** [comment]
I see this is about that; https://www.vice.com/en/article/7k9gya/stanford-scientists-reverse-engineer-moderna-vaccine-post-code-on-github

**Comment by bryan-lunt** [comment]
Thumbs down because this is irrelevant to the repo and not worthy of an issue. Not a vote on the truth or falsehood of the statement.
I recommend that the issue be closed with no further discussion.

**Comment by JC-NYCC-1227** [comment]
> Thumbs down because this is irrelevant to the repo and not worthy of an issue. Not a vote on the truth or falsehood of the statement.
> I recommend that the issue be closed with no further discussion.

Agreed. Sorry, ervinyoung.
