### ISSUE TITLE
sequence as text

### ISSUE THREAD

**Issue by biokomiker** [NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273#35]
Please supply the sequences as text and not as figure. Thanks!

**Comment by mrtnzlml** [comment]
@biokomiker I believe this is already available here: https://github.com/NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273/blob/0d3e8f87e98dde3e781d55f653600425dcd47bc5/Figure1Figure2_032321.fasta

**Comment by biokomiker** [comment]
Thanks - overlooked it !
