### ISSUE TITLE
How to make a person really hairy?

### ISSUE THREAD

**Issue by quetzalsly** [NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273#36]
So now we have the code, someone could write a tool to encode their own mRNA sequences and make their own vaccine or whatever right?

Which bits and bytes do I need to replace to make a human really hairy? it would be cool to have a hairy chest like Sean Connery.

Also while we are at it, could boost testestorone production to become truly alpha male.

We could sell the 'vaccine' on reddit and make a lot of money think about it.

**Comment by NAalytics** [comment]
No- there are many other ingredients to the vaccine and the sequence we published lacks the necessary chemical mods that are added to the RNA. I know the scenario you provide appeals to the Hollywood SciFi spirit in some of us, but it can't be further from our reality.
